### ISSUE TITLE
External commands (helm, kubebox) don't work on Windows

### ISSUE THREAD

**Issue by apetresc** [Krucible/krucible-cli#2]
When trying to run kubebox or helm via krucible on Windows (via Powershell), they both fail with:
```powershell
PS C:\Users\apetrescu> krucible kubebox -c "*****"
panic: exec: "C:\\Users\\apetrescu\\AppData\\Roaming/krucible/bin/kubebox": file does not exist

goroutine 1 [running]:
github.com/Krucible/krucible-cli/cmd.RunBinary(0x1462625, 0x7, 0xc000038340, 0x12, 0xc00019d540, 0x0, 0x2)
        /home/ben/Programming/krucible-cli/cmd/helpers.go:43 +0x2e5
github.com/Krucible/krucible-cli/cmd.glob..func7(0x1fa6e20, 0xc00019d540, 0x0, 0x2)
        /home/ben/Programming/krucible-cli/cmd/kubebox.go:13 +0x73
github.com/spf13/cobra.(*Command).execute(0x1fa6e20, 0xc00019d500, 0x2, 0x2, 0x1fa6e20, 0xc00019d500)
        /home/ben/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:842 +0x2a4
github.com/spf13/cobra.(*Command).ExecuteC(0x1fa7360, 0x444ee1, 0x1f47920, 0xc00005ff78)
        /home/ben/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x31e
github.com/spf13/cobra.(*Command).Execute(...)
        /home/ben/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
github.com/Krucible/krucible-cli/cmd.Execute()
        /home/ben/Programming/krucible-cli/cmd/root.go:26 +0x38
main.main()
        /home/ben/Programming/krucible-cli/main.go:6 +0x27
```
(Exact same thing for `helm` commands).

The binaries it's claiming don't exist actually do:
```powershell
PS C:\Users\apetrescu> ls C:\Users\apetrescu\AppData\Roaming\krucible\bin\


    Directory: C:\Users\apetrescu\AppData\Roaming\krucible\bin


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        2020-07-27   5:48 PM            243 helm
-a----        2020-07-27   5:50 PM       13639015 kubebox
```
I suspect it has something to do with the weird escaping and mixing of path separators that's going on, judging by the error message? If you don't have access to a Windows environment to reproduce/debug, I can give it a shot tonight.

(I'm also not sure I understand why the stack trace has `/home/ben/Programming` hardcoded paths?)

**Comment by apetresc** [comment]
Oh, at least for `helm`, the mystery seems to be solved:
```powershell
PS C:\Users\apetrescu> cat C:\Users\apetrescu\AppData\Roaming\krucible\bin\helm
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>10DF5D2EE80BE743</RequestId><HostId>XQS67ctuBPxEq37aMwurOrr9fFg+TdOxogNKKyVTSFpvJ/4CnXRpmMa7+h0AfZINeaAoXV3TOeQ=</HostId></Error>
```

But the krucible-downloaded kubebox binary is a bit more mysterious. It does appear to be a real binary, `file` agrees:
```bash
$ file /mnt/c/Users/apetrescu/AppData/Roaming/krucible/bin/kubebox
/mnt/c/Users/apetrescu/AppData/Roaming/krucible/bin/kubebox: PE32+ executable (console) x86-64, for MS Windows
```
But Windows can't seem to execute it, even if I just run it manually outside the context of Krucible. It just asks me what I want to open it with. But this is an x86-64 Windows 10 machine so I have no idea why.

**Comment by BenElgar** [comment]
Ah, interesting — thank you for the report! The helm issue was due to a bad path for the Windows binary. I've just pushed a fix for that. I'm not yet sure why the successfully downloaded kubebox binary doesn't seem to work though. I'll investigate more and get back to you.

**Comment by BenElgar** [comment]
The issue was that the binaries had bad names: on Windows an executable is required to have one of a few extensions in order to be allowed to execute. We weren't setting an extension properly and thus the binary could not run. This is now fixed in master and I will cut a new release shortly. Thank you for your help!
